### ISSUE TITLE
Regression from `6.12.4` to `6.13.0`

### ISSUE THREAD

**Issue by Antonio-Laguna** [sanity-io/client#551]
**Describe the bug**

Upon upgrading to `6.13.0` (and then also `6.13.1`) there's a weird regression that goes like this:

```
 ⨯ ../node_modules/.pnpm/@sanity+client@6.13.1/node_modules/@sanity/client/dist/_chunks/browserMiddleware-a-wo4gir.js (79:12) @ onResponse
 ⨯ Internal error: Error: json: unknown field "options"
    at onResponse (../../node_modules/.pnpm/@sanity+client@6.13.1/node_modules/@sanity/client/dist/_chunks/browserMiddleware-a-wo4gir.js:101:19)
    at applyMiddleware (../../node_modules/.pnpm/get-it@8.4.6/node_modules/get-it/dist/_chunks/createRequester-46TmGIk5.js:12:21)
    at onResponse (../../node_modules/.pnpm/get-it@8.4.6/node_modules/get-it/dist/_chunks/createRequester-46TmGIk5.js:76:32)
    at eval (../../node_modules/.pnpm/get-it@8.4.6/node_modules/get-it/dist/_chunks/createRequester-46TmGIk5.js:103:59)
    at onLoad (../../node_modules/.pnpm/get-it@8.4.6/node_modules/get-it/dist/index.react-server.js:251:9)
    at xhr.onreadystatechange (../../node_modules/.pnpm/get-it@8.4.6/node_modules/get-it/dist/index.react-server.js:164:9)
    at eval (../../node_modules/.pnpm/get-it@8.4.6/node_modules/get-it/dist/index.react-server.js:101:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
null
```

While this is an error on Node/Next this also happened on the Studio running the query on the browser. I'd love to get a minimum reproducible case for this but as much as we've tried internally we could not pinpoint the cause of the issue. Removing certain fragments of the query made it work but the same fragments were in other parts and weren't creating any issues so it felt very hit & miss all the time.

We did realise, after pulling our hair for a long time, that pinning the version down to `6.12.4` fixed the issue.

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.29.1 (up to date)
@sanity/google-maps-input    3.0.2 (up to date)
@sanity/icons               2.10.2 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/preview-url-secret   1.6.1 (up to date)
@sanity/rich-date-input      3.0.1 (up to date)
@sanity/ui                   1.9.3 (latest: 2.0.2)
@sanity/vision              3.29.1 (up to date)
sanity                      3.29.1 (up to date)
```

**What operating system are you using?**

macOS

**Which versions of Node.js / npm are you running?**

9.6.7
v18.17.1

**Comment by rexxars** [comment]
Thanks for reporting - should be fixed in [v6.13.3](https://github.com/sanity-io/client/releases/tag/v6.13.3)
