### ISSUE TITLE
Turbopack import error

### ISSUE THREAD

**Issue by rijk** [sanity-io/client#606]
For the latest versions (did not get this in 6.11.1) I am getting the following error when running `next dev --turbo`:

```
 ⨯ TypeError: __TURBOPACK__imported__module__$5b$project$5d2f$node_modules$2f2e$pnpm$2f40$sanity$2b$client$40$6$2e$15$2e$0$2f$node_modules$2f40$sanity$2f$client$2f$dist$2f$index$2e$cjs$2e$js__$5b$app$2d$ssr$5d$__$28$ecmascript$29$__.createClient is not a function
    at /Users/Rijk/Code/Projects/ray2/web/.next/server/chunks/_2d5389._.js:1946:250
    at [project]/lib/sanity/client.ts [app-ssr] (ecmascript) (/Users/Rijk/Code/Projects/ray2/web/.next/server/chunks/_2d5389._.js:1961:3)
    at instantiateModule (/Users/Rijk/Code/Projects/ray2/web/.next/server/chunks/[turbopack]_runtime.js:488:23)
```

Could this have something to do with https://github.com/sanity-io/client/pull/495 maybe?

**Comment by stipsan** [comment]
Hi, give https://github.com/sanity-io/client/releases/tag/v6.15.1 a try and let us know if the problem still persist :)

**Comment by rijk** [comment]
Yep, that did the trick! 👌
