### ISSUE TITLE
Delete using query inside transaction is missing support

### ISSUE THREAD

**Issue by eduardo-marcolino** [sanity-io/client#68]
According to the documentation (https://www.sanity.io/docs/http-mutations#d8ebd1878516l) one should be able to pass a query to delete inside a transaction:

```js
{
  "mutations": [
    {
      "delete": {
        "query": "*[_type == 'feature' && viewCount < $views]",
        "params": {
          "views": 5
        },
      }
    }
  ]
}
```

But doing the following gives an error:

```js
    const transaction = new sanityClient.Transaction()
    transaction.delete({query: '*[_type == "apartment"]'})
    //... other operations
    accountClient.mutate(transaction)
```

```
Error: delete(): "[object Object]" is not a valid document ID
    at Object.exports.validateDocumentId (node_modules/@sanity/client/lib/validators.js:42:11)
    at Transaction._delete [as delete] (node_modules/@sanity/client/lib/data/transaction.js:47:16)
    at Object.importApartmentsTo (/app/netlify/src/provider/accounts.js:45:29)
    at module.exports (app/netlify/src/usecase/handleSingleAccountImport.js:11:18)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.exports.handler (app/netlify/functions/fetch-account.js:19:5)
```

node_modules/@sanity/client/lib/data/transaction.js:46:

```js
  delete: function _delete(documentId) {
    validators.validateDocumentId('delete', documentId);
    return this._add({
      delete: {
        id: documentId
      }
    });
  },
```

I'm using @sanity/client 3.4.1.
is there a way to work around it?

**Comment by bobinska-dev** [comment]
Hello @eduardo-marcolino 👋 
I see what might be an issue here. You are using the "bare http api" logic inside a JS function, but we have a whole [client library prepared especially for JS](https://www.sanity.io/docs/js-client)! This means the JS client based mutations look a bit different than what you see [here](https://www.sanity.io/docs/js-client#delete-documents):

```js
client
  .delete('bike-123')
  .then(() => {
    console.log('Bike deleted')
  })
  .catch((err) => {
    console.error('Delete failed: ', err.message)
  })
```

Hope that helps and feel free to either ask questions in our amazing community [sanity-io-land](https://slack.sanity.io/) or in our SLA slack channel (which your company has access to)
